# Generated by Django 4.0.6 on 2022-07-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='descrizione',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='stelle',
        ),
    ]
